chain:
  name: hydration
  relay_chain: polkadot
  # Local Hydration node
  wss: ws://10.1.20.5:9944
  start_block: 6665454
  #start_block: 6847454
  block_time: 12  # seconds
  finality_threshold: 2  # blocks

database:
  type: postgres
  host: ${HYDRATION_DB_HOST}
  port: ${HYDRATION_DB_PORT}
  name: ${HYDRATION_DB_NAME}
  user: ${HYDRATION_DB_USER}
  password: ${HYDRATION_DB_PASSWORD}
  schema: public

enabled_plugins:
  - common.blocks
  - common.transfers
  - common.balances
  - hydration.omnipool

chain_specific:
  asset_decimals: 12
  native_token: HDX
  min_block_height: 0
  genesis_hash: "0x0000000000000000000000000000000000000000000000000000000000000000" 